comment:
  header: Hi, there.
  footer: "\
    ---\n\n\
    > This is an automated comment created by the [peaceiris/actions-label-commenter]. \
    Responding to the bot or mentioning it won't have any effect."

labels:
  - name: title needs formatting
    labeled:
      pr:
        body: |
        Thank you @{{ pull_request.user.login }} for suggesting this. Please follow the pull request templates.
        The PR template is:
        YYwwWW.D, $USER, HSD_LINK, Flows Effected, Processes Effected, Short Change description.
