comment:
  header: Hi, there.
  footer: "\
    ---\n\n\
    > This is an automated comment created by the [peaceiris/actions-label-commenter]. \
    Responding to the bot or mentioning it won't have any effect."

labels:
  - name: "title needs formatting"
    labeled:
      pr:
        body: "\
          Hi @{{ pull_request.user.login }}. \n\
          You Pull Request title does not follow LV's format.\n\
          Please follow the pull request templates.\n
          The PR template is:\n
          YYwwWW.D, $USER, HSD_LINK, Flows Effected, Processes Effected, Short Change description."
