name: "Label Commenter"

on:
  pull_request_target:
    types: [labeled, unlabeled]

permissions:
  contents: read
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@v1
        with:
          config_file: .github/label-commenter-config.yml
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}